node{
    def buildNo = BUILD_NUMBER
    stage('SCM Checkout'){
        git url: 'https://github.com/ananthand6/docker-hello-world-spring-boot.git'
    }
    try{
    stage(" Maven Clean Package"){
      def mavenHome =  tool name: "maven", type: "maven"
      def mavenCMD = "${mavenHome}/bin/mvn"
      sh "${mavenCMD} clean package"
      
     }
	 stage("JIRA"){
	 def testIssue = [fields: [ project: [key: 'DEMO'],
                                 summary: "New Build Trigger in Jenkins- ${buildNo}",
                                 description: "New build created from jenkin, Build Number ${buildNo}",
                                 issuetype: [name : 'Task']]]

      response = jiraNewIssue issue: testIssue, site: 'JIRA'

      echo response.successful.toString()
      echo response.data.toString()
             
	}
    }
    catch (Exception err) {
        currentBuild.result = 'FAILURE'
                def testIssue = [fields: [ project: [key: 'DEMO'],
                                 summary: "Failure Build number :${buildNo} ",
                                 description: "Build Failed : Build Number ${buildNo}",
                                 issuetype: [name : 'Bug']]]

      response = jiraNewIssue issue: testIssue, site: 'JIRA'

      echo response.successful.toString()
      echo response.data.toString()
    }
        
  }
